### ISSUE TITLE
Make results div drop-able

### ISSUE THREAD

**Issue by mapra99** [mapra99/ip-tracker#16]
Just to give more space to the mobile view, the results should have some show/hide mechanism

**Comment by iagormoraes** [comment]
@mapra99 may I take this issue?

**Comment by mapra99** [comment]
@iagormoraes sure thing!

I was thinking of a button at the end of the results, which shrinks and expands the div like an accordion, and only on mobile view. 
Something like this:
![Mobile](https://user-images.githubusercontent.com/27536621/95108778-56598080-0701-11eb-98c5-92de13682e36.png)
![Mobile (1)](https://user-images.githubusercontent.com/27536621/95108782-56f21700-0701-11eb-96f8-36ac47f3a38c.png)

Let me know what you think!

**Comment by iagormoraes** [comment]
> @iagormoraes sure thing!
> 
> I was thinking of a button at the end of the results, which shrinks and expands the div like an accordion, and only on mobile view.
> Something like this:
> ![Mobile](https://user-images.githubusercontent.com/27536621/95108778-56598080-0701-11eb-98c5-92de13682e36.png)
> ![Mobile (1)](https://user-images.githubusercontent.com/27536621/95108782-56f21700-0701-11eb-96f8-36ac47f3a38c.png)
> 
> Let me know what you think!

I @mapra99 think it would be right positioned, as soon as I open the PR we can align the way you want.
